/* Main.c file generated by New Project wizard
 *
 * Created:   Sun Oct 18 2020
 * Processor: LPC2124
 * Compiler:  GCC for ARM
 */

#include <LPC21xx.h>

int main (void)
 { 
   // Write your code here
   while (1)
      ;
   return 0;
 }   
