/* Main.c file generated by New Project wizard
 *
 * Created:   Fri Oct 16 2020
 * Processor: LPC2134
 * Compiler:  GCC for ARM
 */

#include <LPC213x.h>

int main (void)
 { 
   // Write your code here
   while (1)
      ;
   return 0;
 }   
